name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [master] # branch to trigger deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx 
        pip install sphinx_rtd_theme

    - name: Build Sphinx documentation
      run: |
        sphinx-build -b html docs/ _build/html # Replace 'docs/' with your documentation source directory

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html # The directory where Sphinx output is located
        keep_files: false # This will remove all files in the publishing source branch before copying the new files
        allow_empty_commit: false # This will prevent the action from making a commit if there are no changes to the documentation